### ISSUE TITLE
Are there plans to allow copies of the same sequence via a `count` setting?

### ISSUE THREAD

**Issue by claczny** [Hanziwww/AlphaFold3-GUI#1]
This is a nice project, thank you!
I was wondering if you also intend to integrate functionality to specify copies of individual sequences/entities?
The AlphaFoldServer offers this and it is also part of the `ProteinChain` class (`count`; https://github.com/google-deepmind/alphafold3/blob/2ffe43f574436e6473bf3ab1c0c61c040edc59fd/src/alphafold3/common/folding_input.py#L135).

Thanks a lot!

Best,

Cedric

**Comment by Hanziwww** [comment]
Hi Cedric,

Thank you for your kind words and interest in the project!

However, in previous versions, you could specify multiple copies of sequences or entities by providing multiple IDs separated by commas (e.g., A,B), which would generate copies in the JSON input.

In the latest version v0.2.1, I've introduced an explicit option to specify the copy number for each sequence/entity. This allows you to directly set the number of copies and assign unique IDs to each one if you prefer. So now, both methods are supported—you can continue using the comma-separated IDs or utilize the new copy number feature.

![image](https://github.com/user-attachments/assets/13600b55-2868-4f66-8626-04bce17b97be)


This update aligns with the functionality provided by the AlphaFoldServer and the ProteinChain class's count parameter you mentioned.

I hope this enhancement makes the tool even more convenient for your needs. Thank you for your feedback, and please feel free to share any other suggestions!

Best regards,

Hanzi

**Comment by claczny** [comment]
Hi Hanzi,

wow, that was super fast! Great, thanks a lot!

Just so that I understand, if you had a sequence, say `>MINDME` before, and under `Entity ID(s)`, one would specify `A1, A2, A3`, it would create 3 copies of `MINDME` and fold this three-mer?
Is this also the default behavior in AlphaFold(3) or would your GUI have translated it into three sequences in the `JSON` output?

**Comment by Hanziwww** [comment]
Hi Cedric,

In AlphaFold 3, when you provide a JSON like this:

```json
"protein": {
    "sequence": "MINDME",
    "id": [
        "A1",
        "A2",
        "A3"
    ]
}
```

AlphaFold 3 will automatically interpret this as needing to create copies of the sequence for each ID, without requiring translation by the GUI. In recent updates, if the number of copies is specified, the GUI will generate the appropriate JSON format accordingly.
